const schools = { // eslint-disable-line no-unused-vars
	'Abbeyfields School': 'abbeyfields',
	'Adelaide Primary School': 'adelaide',
	'All Hallows Catholic College': 'allhallows',
	'All Souls Catholic Primary School': 'allsouls',
	'ALP Trust': 'alptrust',
	'Alperton Community School': 'alperton',
	'Ansford Academy': 'ansford',
	'Ashley Primary': 'ashleyprimary',
	'Aston Manor School': 'astonmanor',
	'Aylesbury High School': 'aylesburyhigh',
	'Bamburgh school': 'bamburghschool',
	'Bede Burn': 'bede',
	'Bedlingtonshire Community School': 'bchschool',
	'Belmont School': 'belmont',
	'Biddick Academy': 'biddickacademy',
	'Biddick Hall Infants': 'biddickhallinfants',
	'Biddick Hall Juniors': 'biddickhall',
	'Birmingham Ormiston Academy': 'boa',
	'Bishop Cleary Catholic Multi Academy': 'bccma',
	'Boldon Nursery': 'boldonnursery',
	'Boroughbridge High School': 'boroughbridgehigh',
	'Bosworth Academy': 'bosworth',
	'Bosworth MAT': 'bosworthmat',
	'Bothal Primary': 'bothal',
	'Brooklands Farm Primary School': 'brooklands',
	'Brookvale-Groby': 'grobycollege',
	'Bucklers Mead Academy': 'bmcs',
	'Caedmon College': 'caedmon',
	'Cardinal Wiseman Catholic School': 'cardinalwiseman',
	'Central Primary': 'centralprimary',
	'Channeling Positivity': 'channelingpositivity',
	Chantry: 'chantry3rivers',
	'Chatsmore Catholic High School': 'chatsmore',
	'Chelsea Academy': 'chelsea',
	'Chester-le-Street CofE Primary': 'chesterlestreet',
	'Christ Church Primary': 'christchurchprimary',
	'Christopher Pickering Primary School': 'christopherpickering',
	'Clervaux Nursery': 'clervaux',
	'Cockshut Hill Technology College': 'cockshut',
	'Court Fields Community School': 'courtfields',
	'Crosby High School': 'crosby',
	'CTC Mail': 'ctcmail',
	'Darton College': 'darton',
	DCAT: 'chichestermat',
	'Debden Park High School': 'dphs',
	'Demeter House School': 'demeter',
	'Denbigh Primary School': 'denbighprimary',
	'Denton Community College': 'denton',
	'Dunn Street Primary School': 'dunnstreet',
	'Durham Community Business College- Durham Federation': 'durhamcommunity',
	'East Boldon Infants': 'eastboldoninfants',
	'East Boldon Junior School': 'eastboldonjuniors',
	'East Street Arts': 'eaststreet',
	'Easthampstead Park School': 'easthampstead',
	'Edward Peake C of E Middle School': 'edwardpeake',
	'Elizabeth Woodville': 'ews',
	'Elstree UTC': 'elstree',
	EMSCI: 'emsci',
	'Enfield Grammar School': 'enfield',
	'Erdington was Kingsbury School &amp; Sports College': 'kingsbury',
	Evolve: 'ipsative',
	'Fab Lab': 'fablab',
	'Faith Primary School': 'faithps',
	'Fellgate Primary': 'fellgate',
	'Felsted School': 'felsted',
	'Fitness Challenge': 'fitness',
	'forest view': 'forestview',
	"Freeman's Endowed CE Junior School": 'feceja',
	'Fyndoune Community College - Durham Federation': 'fyndourne',
	'Graham James Primary School': 'grahamjames',
	'Gravesend Grammar School': 'ggs',
	'Green Top Primary School': 'greentop',
	'Hadrian Primary': 'hadrianprimary',
	'Harton Primary': 'harton',
	'Hartsdown Academy': 'hartsdown',
	'Hatchell Wood Primary School': 'hatchellwood',
	'Heartlands High School': 'heartlands',
	'Heathfield Community School': 'heathfield',
	'hebburn lakes': 'hebburnlakes',
	'Hedworth Lane Primary School South Tyneside': 'hedworthlaneprimary',
	'Hedworthfield Primary School': 'hedworthfield',
	'Helen Gibson Nursery': 'helengibson',
	'Hillview Primary School': 'hillview',
	'Hitchin Boys School': 'hitchin',
	'Holy Trinity CE Primary School': 'holytrinityce',
	'Homewood School &amp; 6th Form Centre': 'homewood',
	'Horbury Bridge Academy': 'horburybridgeacademy',
	'Humber Educational Trust': 'het',
	'Hyde Community College': 'hyde',
	'Inspiring Leaders': 'inspiringleaders',
	'Jarrow Cross': 'jarrowcross',
	JMSS: 'jmss',
	'John Hampden Grammar School': 'johnhampden',
	'John Henry Newman Catholic College': 'jhncc',
	'Joseph Swan Academy': 'josephswanacademy',
	'Kingsford Community School': 'kingsford',
	'Kingsmeadow Community School': 'kingsmeadow',
	'Knights Templar School': 'ktemplar',
	'Langtree School': 'langtree',
	Lawnswood: 'lawnswood',
	'Laygate Primary School': 'laygateprimary',
	'Lichfield Diocesan Board of Education': 'lichfielddbe',
	'Lister Community Secondary School': 'lcss',
	'Lliswerry High School': 'lliswerry',
	'Longthorpe Primary School': 'longthorpe',
	'Lord Blyton Primary School': 'lordblyton',
	'Lord Lawson of Beamish Academy': 'lawson',
	'Manchester Communication Academy': 'mca',
	'Manor School And Sports College': 'manorschool',
	'Marden High School': 'mardenhigh',
	'Marine Park Primary School': 'marinepark',
	'marsden primary': 'marsdenprimary',
	'Monkton Infants': 'monkton',
	'Mortimer Primary School': 'mortimerprimary',
	'New Horizons School': 'newhorizons',
	'Newbridge High School': 'newbridgehigh',
	Newminster: 'newminster3rivers',
	'Nightingale Lawnswood': 'nightingale',
	'Ninestiles TSA': 'ninstiles',
	'Northern Lights SCITT Site': 'northernlights',
	'Northumberland Park School': 'npcs',
	'Oaks Park School': 'oakspark',
	'Oathall Community College': 'oathall',
	'Oldbury Wells School': 'oldbury',
	'Park View School': 'parkview',
	'Parrs Wood High School': 'pwhs',
	'Percy Hedley School- PHS': 'percyhedleyschool',
	'Percy Hedley- College': 'percyhedleycollege',
	'Percy Hedley- Foundation': 'percyhedleyfoundation',
	'Percy Hedley- NCS': 'northerncountiesschool',
	'Poole High School': 'phslearning',
	'Poynton High School (KED)': 'poyntonhs',
	'Queens School': 'queenssch',
	'Queensmead School': 'queensmead',
	'Quintin Kynaston': 'qk',
	'Redmoor Academy': 'redmoor',
	'Rednock School': 'rednock',
	'Rhyddings Business and Enterprise School': 'rhyddings',
	'Robert Mays School': 'robertmay',
	'Sacred Heart Catholic Primary School': 'shcps',
	'Salvatorian College': 'salvatorian',
	'Samuel Lister Academy': 'samuellister',
	Sandbox: 'sandbox',
	'Sandringham School': 'sandringham',
	'Seaview School': 'seaview',
	'Selby High School': 'selby',
	'Sheffield High School': 'shs',
	'Shipston High School': 'shipston',
	'Shirebrook Academy': 'shirebrook',
	'Simon Balle School': 'sbs',
	Simonside: 'simonside',
	"Sir William Borlase's Grammar School": 'swbgs',
	'Smart Academy': 'smartacademy',
	smartassess: 'smartassess',
	'South Birmingham SCITT': 'southbirminghamscitt',
	'south tyneside': 's-tyneside',
	"SS Mary &amp; John's": 'ssmaryjohns',
	'SS Peter and Paul Catholic Primary Academy': 'giffardprimary',
	'St Aloysius': 'st-aloysius',
	"St Anne's CofE Primary": 'stannes',
	'St Bedes Primary School': 'stbedesjarrow',
	'St Bedes RC South Tyneside': 'stbedesrc',
	"St Bonaventure's": 'sbrc',
	'St Chads Academy Trust': 'scat',
	"St Edmund's Catholic Academy": 'edmunds',
	'St Giles Academy': 'chadvarah',
	'St Gregorys School South Tyneside': 'stgregorys',
	'St Joan of Arc School': 'joa',
	'St John Fisher Catholic Voluntary Academy': 'johnfisher',
	"St John's CE Primary School": 'stjceps',
	'St Johns Church School': 'stjohnsprimary',
	"St Joseph's Catholic High School": 'sjchs',
	'St Josephs': 'stjosephs',
	'St Julians': 'stjulians',
	"St Mary's": 'stmarysst',
	"St Mary's Catholic School": 'stmarysnc',
	'St Matthews Catholic Primary School': 'smcps',
	"St Michael's Primary Academy": 'smpa',
	'St Oswalds CE Aided Primary': 'st-oswalds.realsmartcloud.com',
	'St Oswalds RC Voluntary Primary South Tyneside': 'stoswaldsrc',
	'St Peter St Pauls': 'sspeterpaul',
	'St Peters Collegiate C of E School': 'spc',
	"St Teresa's Primary Academy": 'stteresas',
	'St Thomas More Catholic School': 'stm',
	'St Thomas More Partnership': 'stmpos',
	'Stanhope Primary': 'stanhopeprimary',
	'Stannington First School': 'stannington',
	'Stokesley School': 'stokesley',
	'Studley High School': 'studleyhigh',
	'Studley Shires TSA': 'shirestsa',
	'Sue Hedley Nursery': 'suehedley',
	'Temple Moor High School': 'templemoor',
	'The Beacon Centre': 'laygate2',
	'The Braybrook Centre': 'braybrook',
	'The Bushey Academy': 'busheyacademy',
	'The Causeway School': 'causeway',
	'The Durham Federation': 'durham',
	'The East Manchester Academy': 'temac',
	'The English School': 'tesc',
	'The Grangefield Academy': 'grangefield',
	'The King Edward VI High School': 'kevi',
	'The Lenham School': 'swadelands',
	'The Littlehampton Academy': 'littlehampton',
	'The Manchester Health Academy': 'tmha',
	'The Midpoint Centre': 'midpoint',
	'The Northumberland Church of England Academy': 'ncea',
	'The Orchard Centre': 'orchard',
	'The Petersfield School': 'petersfield',
	'The St Lawrence Academy': 'thestlawrenceacademy',
	'The UCL Academy': 'uclacademy',
	'Thurston Outdoor Education Centre': 'thurston',
	'Titan Partnership - St. Georges Academy': 'titan',
	'Toner Avenue': 'toner',
	'Trinity (Sevenoaks)': 'trinitysevenoaks',
	'Trinity Catholic College': 'trinitycc',
	'Username policy testing school': 'upts',
	'UTC Bolton': 'utcbolton',
	'Valley Gardens Middle School': 'valleygardens',
	'Valley View': 'valleyview',
	'Walbottle Campus': 'walbottle',
	'West Boldon Primary School': 'westboldon',
	'West Oaks School': 'westoaks',
	'Whalley Range High School': 'whalley',
	'Whickham School &amp; Sports College': 'whickhamschool',
	'Whitburn Village Primary School': 'whitburnvillage',
	'Whitefield Primary School': 'whitefield',
	'Winstanley Community College': 'winstanley',
	'Winyates Primary School': 'winyates',
	'Wirral Grammar School for Girls': 'wgsg',
	'Woodcroft Primary': 'woodcroft',
	'XP East': 'xpeast',
	'XP School': 'xp',
	'xxBrook Vale Schoolxx': 'brookvale',
	'xxGroby Collegexx': 'groby',
};

const search = { // eslint-disable-line no-unused-vars
	'Abbeyfields School': '/sc_logos/Abbeyfields logo.jpg',
	'Adelaide Primary School': '/sc_logos/myschoollogo.jpg',
	'All Hallows Catholic College': '/sc_logos/All Hallows Left_COL_1.jpg',
	'All Souls Catholic Primary School': '/sc_logos/Logo2.jpg',
	'ALP Trust': '/sc_logos/myschoollogo.jpg',
	'Alperton Community School': '/sc_logos/logo-13-6-17.jpg',
	'Ansford Academy': '/sc_logos/myschoollogo.jpg',
	'Ashley Primary': '/sc_logos/Garden.jpg',
	'Aston Manor School': '/sc_logos/NEW AMA LOGO.png',
	'Aylesbury High School': '/sc_logos/Screen Shot 2014-11-13 at 11.44.21.png',
	'Bamburgh school': '/sc_logos/Bamburgh-logo.png',
	'Bede Burn': '/sc_logos/myschoollogo.jpg',
	'Bedlingtonshire Community School': '/sc_logos/logo02.jpg',
	'Belmont School': '/sc_logos/Tree_75x75.png',
	'Biddick Academy': '/sc_logos/myschoollogo.jpg',
	'Biddick Hall Infants': '/sc_logos/myschoollogo.jpg',
	'Biddick Hall Juniors': '/sc_logos/myschoollogo.jpg',
	'Birmingham Ormiston Academy': '/sc_logos/BOAIcon.png',
	'Bishop Cleary Catholic Multi Academy': '/sc_logos/logo.jpg',
	'Boldon Nursery': '/sc_logos/myschoollogo.jpg',
	'Boroughbridge High School': '/sc_logos/myschoollogo.jpg',
	'Bosworth Academy': '/sc_logos/BOS_Block_Logo_CMYK-01_75x75.jpg',
	'Bosworth MAT': '/sc_logos/myschoollogo.jpg',
	'Bothal Primary': '/sc_logos/myschoollogo.jpg',
	'Brooklands Farm Primary School': '/sc_logos/Master logo large.jpg',
	'Brookvale-Groby': '/sc_logos/GROBY-Logo-WhiteBG.png',
	'Bucklers Mead Academy': '/sc_logos/Screen Shot 2014-01-30 at 10.44.34.png',
	'Caedmon College': '/sc_logos/CCWsmall.png',
	'Cardinal Wiseman Catholic School': '/sc_logos/badgeonlysmall.gif',
	'Central Primary': '/sc_logos/myschoollogo.jpg',
	'Channeling Positivity': '/sc_logos/Screen Shot 2015-05-19 at 11.23.31.png',
	Chantry: '/sc_logos/Chantry logo.jpg',
	'Chatsmore Catholic High School': '/sc_logos/CCHS-RLSMART-Logo.jpg',
	'Chelsea Academy': '/sc_logos/chelsea_logo.png',
	'Chester-le-Street CofE Primary': '/sc_logos/Logo.png',
	'Christ Church Primary': '/sc_logos/myschoollogo.jpg',
	'Christopher Pickering Primary School': '/sc_logos/myschoollogo.jpg',
	'Clervaux Nursery': '/sc_logos/myschoollogo.jpg',
	'Cockshut Hill Technology College': '/sc_logos/Cockshut.jpg',
	'Court Fields Community School': '/sc_logos/logo_6.jpg',
	'Crosby High School': '/sc_logos/crosby logo final v2 OL.jpg',
	'CTC Mail': '/sc_logos/lepp.jpg',
	'Darton College': '/sc_logos/Darton College.gif',
	DCAT: '/sc_logos/DCAT_colour_logo_SM.jpg',
	'Debden Park High School': '/sc_logos/debdenpark.png',
	'Demeter House School': '/sc_logos/myschoollogo.jpg',
	'Denbigh Primary School': '/sc_logos/Denbigh primary 120.jpg',
	'Denton Community College': '/sc_logos/Screen Shot 2014-12-02 at 14.06.04.png',
	'Dunn Street Primary School': '/sc_logos/myschoollogo.jpg',
	'Durham Community Business College- Durham Federation': '/sc_logos/myschoollogo.jpg',
	'East Boldon Infants': '/sc_logos/myschoollogo.jpg',
	'East Boldon Junior School': '/sc_logos/myschoollogo.jpg',
	'East Street Arts': '/sc_logos/myschoollogo.jpg',
	'Easthampstead Park School': '/sc_logos/EPCS Logo in black.png',
	'Edward Peake C of E Middle School': '/sc_logos/nsg.jpg',
	'Elizabeth Woodville': '/sc_logos/images.jpg',
	'Elstree UTC': '/sc_logos/Screen Shot 2014-09-02 at 13.09.38.png',
	EMSCI: '/sc_logos/logo_8.jpg',
	'Enfield Grammar School': '/sc_logos/myschoollogo.jpg',
	'Erdington was Kingsbury School &amp; Sports College': '/sc_logos/kingsbury logo2a_RGB_w.jpg',
	Evolve: '/sc_logos/Ipsative Small.png',
	'Fab Lab': '/sc_logos/myschoollogo.jpg',
	'Faith Primary School': '/sc_logos/myschoollogo.jpg',
	'Fellgate Primary': '/sc_logos/myschoollogo.jpg',
	'Felsted School': '/sc_logos/colour shield.jpg',
	'Fitness Challenge': '/sc_logos/myschoollogo.jpg',
	'forest view': '/sc_logos/myschoollogo.jpg',
	'Freeman\'s Endowed CE Junior School': '/sc_logos/myschoollogo.jpg',
	'Fyndoune Community College - Durham Federation': '/sc_logos/myschoollogo.jpg',
	'Graham James Primary School': '/sc_logos/myschoollogo.jpg',
	'Gravesend Grammar School': '/sc_logos/GGS 2016 logo in RGB.jpg',
	'Green Top Primary School': '/sc_logos/logo-greentop.png',
	'Hadrian Primary': '/sc_logos/myschoollogo.jpg',
	'Harton Primary': '/sc_logos/myschoollogo.jpg',
	'Hartsdown Academy': '/sc_logos/myschoollogo.jpg',
	'Hatchell Wood Primary School': '/sc_logos/Logo Large.jpg',
	'Heartlands High School': '/sc_logos/logo-2.jpg',
	'Heathfield Community School': '/sc_logos/resized_oak_leaf.jpg',
	'hebburn lakes': '/sc_logos/myschoollogo.jpg',
	'Hedworth Lane Primary School South Tyneside': '/sc_logos/myschoollogo.jpg',
	'Hedworthfield Primary School': '/sc_logos/myschoollogo.jpg',
	'Helen Gibson Nursery': '/sc_logos/myschoollogo.jpg',
	'Hillview Primary School': '/sc_logos/myschoollogo.jpg',
	'Hitchin Boys School': '/sc_logos/FOUNDATION 1632 BADGE WITHOUT TEXT ok.jpg',
	'Holy Trinity CE Primary School': '/sc_logos/myschoollogo.jpg',
	'Homewood School &amp; 6th Form Centre': '/sc_logos/Homewood_Logo.jpg',
	'Horbury Bridge Academy': '/sc_logos/myschoollogo.jpg',
	'Humber Educational Trust': '/sc_logos/myschoollogo.jpg',
	'Hyde Community College': '/sc_logos/new hyde logo.jpg',
	'Inspiring Leaders': '/sc_logos/Screen Shot 2014-10-03 at 12.53.27.png',
	'Jarrow Cross': '/sc_logos/myschoollogo.jpg',
	JMSS: '/sc_logos/jm logo.png',
	'John Hampden Grammar School': '/sc_logos/myschoollogo.jpg',
	'John Henry Newman Catholic College': '/sc_logos/JHN Logo small.gif',
	'Joseph Swan Academy': '/sc_logos/Logo_1.jpg',
	'Kingsford Community School': '/sc_logos/Picture5.jpg',
	'Kingsmeadow Community School': '/sc_logos/km_logo.gif',
	'Knights Templar School': '/sc_logos/KTS badge - crest.jpg',
	'Langtree School': '/sc_logos/Screen Shot 2015-07-13 at 14.52.25.png',
	Lawnswood: '/sc_logos/myschoollogo.jpg',
	'Laygate Primary School': '/sc_logos/myschoollogo.jpg',
	'Lichfield Diocesan Board of Education': '/sc_logos/myschoollogo.jpg',
	'Lister Community Secondary School': '/sc_logos/ListerLogoROUND75x75.png',
	'Lliswerry High School': '/sc_logos/logo2.JPG',
	'Longthorpe Primary School': '/sc_logos/myschoollogo.jpg',
	'Lord Blyton Primary School': '/sc_logos/myschoollogo.jpg',
	'Lord Lawson of Beamish Academy': '/sc_logos/Screen Shot 2013-12-13 at 11.07.47.png',
	'Manchester Communication Academy': '/sc_logos/Manc_Com_Ac.jpg',
	'Manor School And Sports College': '/sc_logos/diamond jpg.jpg',
	'Marden High School': '/sc_logos/b_and_w.jpg',
	'Marine Park Primary School': '/sc_logos/myschoollogo.jpg',
	'marsden primary': '/sc_logos/myschoollogo.jpg',
	'Monkton Infants': '/sc_logos/myschoollogo.jpg',
	'Mortimer Primary School': '/sc_logos/myschoollogo.jpg',
	'New Horizons School': '/sc_logos/NH logo.PNG',
	'Newbridge High School': '/sc_logos/Screen Shot 2016-03-21 at 10.25.21.png',
	Newminster: '/sc_logos/Newminster logo.jpg',
	'Nightingale Lawnswood': '/sc_logos/myschoollogo.jpg',
	'Ninestiles TSA': '/sc_logos/myschoollogo.jpg',
	'Northern Lights SCITT Site': '/sc_logos/myschoollogo.jpg',
	'Northumberland Park School': '/sc_logos/School Logo.jpg',
	'Oaks Park School': '/sc_logos/4XsTAnLp.jpeg',
	'Oathall Community College': '/sc_logos/new75logo.jpg',
	'Oldbury Wells School': '/sc_logos/OWSlogo.png',
	'Park View School': '/sc_logos/Park View School_1.jpg',
	'Parrs Wood High School': '/sc_logos/pwhs-logo.jpg',
	'Percy Hedley School- PHS': '/sc_logos/myschoollogo.jpg',
	'Percy Hedley- College': '/sc_logos/myschoollogo.jpg',
	'Percy Hedley- Foundation': '/sc_logos/myschoollogo.jpg',
	'Percy Hedley- NCS': '/sc_logos/myschoollogo.jpg',
	'Poole High School': '/sc_logos/Blue dolphin (google size).jpg',
	'Poynton High School (KED)': '/sc_logos/myschoollogo.jpg',
	'Queens School': '/sc_logos/Queens-Logo-White-BG.png',
	'Queensmead School': '/sc_logos/Realsmart Favicon.jpg',
	'Quintin Kynaston': '/sc_logos/QK_optimised.png',
	'Redmoor Academy': '/sc_logos/JUST R.jpg',
	'Rednock School': '/sc_logos/school_logo.png',
	'Rhyddings Business and Enterprise School': '/sc_logos/logo_1.png',
	'Robert Mays School': '/sc_logos/robert-mays.png',
	'Sacred Heart Catholic Primary School': '/sc_logos/myschoollogo.jpg',
	'Salvatorian College': '/sc_logos/small logo.png',
	'Samuel Lister Academy': '/sc_logos/SLA---main-logo---green-and-purple.gif',
	Sandbox: '/sc_logos/myschoollogo.jpg',
	'Sandringham School': '/sc_logos/sandringham logo.jpg',
	'Seaview School': '/sc_logos/myschoollogo.jpg',
	'Selby High School': '/sc_logos/myschoollogo.jpg',
	'Sheffield High School': '/sc_logos/Sheffield Girls_ - Generic Logo.jpg',
	'Shipston High School': '/sc_logos/myschoollogo.jpg',
	'Shirebrook Academy': '/sc_logos/SA logo2.JPG',
	'Simon Balle School': '/sc_logos/Badge no background.JPG',
	Simonside: '/sc_logos/myschoollogo.jpg',
	'Sir William Borlase\'s Grammar School': '/sc_logos/SWBS.jpg',
	'Smart Academy': '/sc_logos/smart_academy_logo_red.png',
	smartassess: '/sc_logos/avatar.png',
	'South Birmingham SCITT': '/sc_logos/myschoollogo.jpg',
	'south tyneside': '/sc_logos/myschoollogo.jpg',
	'SS Mary & John\'s': '/sc_logos/SS Mary and Johns Logo.jpg',
	'SS Peter and Paul Catholic Primary Academy': '/sc_logos/SS Peter and Paul.jpg',
	'St Aloysius': '/sc_logos/St. Aloysius Square Logos Various-05.png',
	'St Anne\'s CofE Primary': '/sc_logos/myschoollogo.jpg',
	'St Bedes Primary School': '/sc_logos/myschoollogo.jpg',
	'St Bedes RC South Tyneside': '/sc_logos/myschoollogo.jpg',
	'St Bonaventure\'s': '/sc_logos/St Bonaventures Logo White small.jpg',
	'St Chads Academy Trust': '/sc_logos/myschoollogo.jpg',
	'St Edmund\'s Catholic Academy': '/sc_logos/St Edmund_s Logo.jpg',
	'St Giles Academy': '/sc_logos/st giles logo.JPG',
	'St Gregorys School South Tyneside': '/sc_logos/myschoollogo.jpg',
	'St Joan of Arc School': '/sc_logos/School Logo_2.jpg',
	'St John Fisher Catholic Voluntary Academy': '/sc_logos/sjflogo.png',
	'St John\'s CE Primary School': '/sc_logos/Screen Shot 2015-12-01 at 10.23.29.png',
	'St Johns Church School': '/sc_logos/myschoollogo.jpg',
	'St Joseph\'s Catholic High School': '/sc_logos/logo_150x150.jpg',
	'St Josephs': '/sc_logos/myschoollogo.jpg',
	'St Julians': '/sc_logos/myschoollogo.jpg',
	'St Mary\'s': '/sc_logos/myschoollogo.jpg',
	'St Mary\'s Catholic School': '/sc_logos/logo-transparent-75-by-75.png',
	'St Matthews Catholic Primary School': '/sc_logos/St Matthews - colour logo.png',
	'St Michael\'s Primary Academy': '/sc_logos/STM-Logo.jpg',
	'St Oswalds CE Aided Primary': '/sc_logos/myschoollogo.jpg',
	'St Oswalds RC Voluntary Primary South Tyneside': '/sc_logos/myschoollogo.jpg',
	'St Peter St Pauls': '/sc_logos/myschoollogo.jpg',
	'St Peters Collegiate C of E School': '/sc_logos/shellStPetersLogo_02.png',
	'St Teresa\'s Primary Academy': '/sc_logos/stt.jpg',
	'St Thomas More Catholic School': '/sc_logos/CrestLogo.jpg',
	'St Thomas More Partnership': '/sc_logos/myschoollogo.jpg',
	'Stanhope Primary': '/sc_logos/myschoollogo.jpg',
	'Stannington First School': '/sc_logos/stannington first school.png',
	'Stokesley School': '/sc_logos/myschoollogo.jpg',
	'Studley High School': '/sc_logos/studley-high-school-shield -New.jpg',
	'Studley Shires TSA': '/sc_logos/myschoollogo.jpg',
	'Sue Hedley Nursery': '/sc_logos/TREE (COLOUR).jpg',
	'Temple Moor High School': '/sc_logos/TMHS Logo (new).jpg',
	'The Beacon Centre': '/sc_logos/myschoollogo.jpg',
	'The Braybrook Centre': '/sc_logos/myschoollogo.jpg',
	'The Bushey Academy': '/sc_logos/Bushey logo.jpg',
	'The Causeway School': '/sc_logos/unnamed (1).jpg',
	'The Durham Federation': '/sc_logos/logo_5.png',
	'The East Manchester Academy': '/sc_logos/TEMA RGB.jpg',
	'The English School': '/sc_logos/TESLogo.jpg',
	'The Grangefield Academy': '/sc_logos/Grangefield logo_FC.jpg',
	'The King Edward VI High School': '/sc_logos/KeviLogo75.jpg',
	'The Lenham School': '/sc_logos/The Lenham School (Mini).jpg',
	'The Littlehampton Academy': '/sc_logos/tla_logo.gif',
	'The Manchester Health Academy': '/sc_logos/150 x 150.png',
	'The Midpoint Centre': '/sc_logos/myschoollogo.jpg',
	'The Northumberland Church of England Academy': '/sc_logos/ncea_logo.png',
	'The Orchard Centre': '/sc_logos/myschoollogo.jpg',
	'The Petersfield School': '/sc_logos/TPS new colour logo July 2011 CMYK.JPG',
	'The St Lawrence Academy': '/sc_logos/St Lawrence Logo Main.jpg',
	'The UCL Academy': '/sc_logos/Screen Shot 2015-03-10 at 10.26.00.png',
	'Thurston Outdoor Education Centre': '/sc_logos/myschoollogo.jpg',
	'Titan Partnership - St. Georges Academy': '/sc_logos/Logo_2.jpg',
	'Toner Avenue': '/sc_logos/myschoollogo.jpg',
	'Trinity (Sevenoaks)': '/sc_logos/icon_web.fw realsmart.png',
	'Trinity Catholic College': '/sc_logos/Trinity-rings2.png',
	'Username policy testing school': '/sc_logos/myschoollogo.jpg',
	'UTC Bolton': '/sc_logos/myschoollogo.jpg',
	'Valley Gardens Middle School': '/sc_logos/myschoollogo.jpg',
	'Valley View': '/sc_logos/myschoollogo.jpg',
	'Walbottle Campus': '/sc_logos/400-white-full.png',
	'West Boldon Primary School': '/sc_logos/myschoollogo.jpg',
	'West Oaks School': '/sc_logos/for twitter.jpg',
	'Whalley Range High School': '/sc_logos/School Badge square real.jpg',
	'Whickham School &amp; Sports College': '/sc_logos/Screen Shot 2011-09-13 at 12.24.45.png',
	'Whitburn Village Primary School': '/sc_logos/myschoollogo.jpg',
	'Whitefield Primary School': '/sc_logos/logo_9.jpg',
	'Winstanley Community College': '/sc_logos/myschoollogo.jpg',
	'Winyates Primary School': '/sc_logos/myschoollogo.jpg',
	'Wirral Grammar School for Girls': '/sc_logos/Badge.jpg',
	'Woodcroft Primary': '/sc_logos/treehouse.png',
	'XP East': '/sc_logos/myschoollogo.jpg',
	'XP School': '/sc_logos/XP_LOGO_BLACK_no strap_72dpi.jpg',
	'xxBrook Vale Schoolxx': '/sc_logos/myschoollogo.jpg',
	'xxGroby Collegexx': '/sc_logos/myschoollogo.jpg',
};
